### ISSUE TITLE
Hovers are queried for positions beyond the end of the line

### ISSUE THREAD

**Issue by sqs** [sourcegraph/codeintellify#37]
Repro:

1. Go to https://sourcegraph.com/github.com/ReactiveX/rxjs/-/blob/src/internal/observable/SubscribeOnObservable.ts
2. Enable extensions (the internal Sourcegraph feature flag)
3. Enable the blame extension
4. Hover over the blame annotation after a line

Eventually this hover turns red because the over requested is for 1 character after the end of the line.

It seems that if there is a `LineDecorationAttachment` after a line, hovering it triggers a hover on that line, but for the wrong character.

![screenshot from 2018-08-10 16-14-49](https://user-images.githubusercontent.com/1976/43984930-89b2b7d6-9cb8-11e8-972d-66da68b75cca.png)

**Comment by sqs** [comment]
@ijsnow When I hover the after-line `LineDecorationAttachment`, it calls the `domFunction` `getLineNumberFromCodeElement` with the `td.code.annotated`. I would like to have the following logic:

> If the hover's `target` is a `.line-decoration-attachment` (which is a child of the element passed to `getLineNumberFromCodeElement`, then DO NOT try to show a hover for it.

Can you give me a pointer to where this would be done?

**Comment by ijsnow** [comment]
You want to filter it out from `DOMFunctions.getCodeElementFromTarget`. If you filter it from there, it'll never reach `getLineNumberFromCodeElement`. This was already done for blames in the Sourcegraph web app:

```javascript
if (target.classList.contains('blame') || target.classList.contains('blame__contents')) {
  return null
}
```

**Comment by sqs** [comment]
Nice, thanks!
