### ISSUE TITLE
Empty hover contents

### ISSUE THREAD

**Issue by sqs** [sourcegraph/codeintellify#39]
The definition name token of `DiagnosticAnalyzer` at https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticAnalyzer.cs has empty contents:

![image](https://user-images.githubusercontent.com/1976/44073874-0d211a56-9f4b-11e8-886c-ffc063b3c1eb.png)

Reported by @joshuakgoldberg: https://twitter.com/JoshuaKGoldberg/status/1029234692703191040

**Comment by felixfbecker** [comment]
I doubt that this is a codeintellify issue - the experimental C# code intelligence rarely works for me. I can't even repro right now because the server does not respond. Do you remember the hover response in the network tab?

**Comment by felixfbecker** [comment]
As suspected, the langserver returns an empty content:
```json
[{"id":0,"result":{"capabilities":{"hoverProvider":true,"completionProvider":{},"signatureHelpProvider":{"triggerCharacters":["("]},"definitionProvider":true,"referencesProvider":true,"documentHighlightProvider":true,"workspaceSymbolProvider":true,"codeLensProvider":{"resolveProvider":true},"documentFormattingProvider":true,"documentRangeFormattingProvider":true,"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"}","moreTriggerCharacter":[";"]},"renameProvider":true}},"jsonrpc":"2.0"},{"id":1,"result":{"contents":" "},"jsonrpc":"2.0"},{"id":2,"result":null,"jsonrpc":"2.0"}]
```

**Comment by felixfbecker** [comment]
@JoshuaKGoldberg we use https://github.com/OmniSharp/omnisharp-node-client, which is an LSP wrapper for OmniSharp. We build it here: https://github.com/sourcegraph/lsp-adapter/tree/master/dockerfiles/csharp
