### ISSUE TITLE
Delay hiding the tooltip when mouse is moved away

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/codeintellify#48]
Reported in https://github.com/sourcegraph/issues/issues/132

> - sourcegraph.com
> - Chrome Version 68.0.3440.106 (Official Build) (64-bit), OSX 10.13.6
> 
> #### Steps to reproduce:
> 
> 1. Go here: https://sourcegraph.com/github.com/src-d/go-git/-/blob/options.go#L325
> 2. Hover the mouse over an identifier (e.g: `All` attribute inside `CommitOptions`)
> 3. Quickly move the mouse towards the "Find references" button
> 
> #### Expected: 
> - Popup should remain in place and let me click on find references
> 
> #### Actual:
> - Sometimes the popup disappear, probably because it thinks the mouse isn't hovering over the identifier anymore
> 
> I'll post a link to a video with the repro in a follow-up update.

**Comment by sqs** [comment]
@nictuku added a video on the original issue:

https://photos.app.goo.gl/TnmuYnd5Henjrk3e8

**Comment by Joelkw** [comment]
@macraig adding this to our backlog from our prior discussion but noting this isn't a near or medium term priority for us (and has been sitting for two years it looks like).

**Comment by mrnugget** [comment]
@Joelkw Can we bump this? We've talked about this on Slack a few weeks ago (thread got deleted).

IMHO this is a critical issue because it's something a new user can run into in their first seconds of using Sourcegraph and it causes frustration.

**Comment by mrnugget** [comment]
Just discussed this on Slack and [it sounds like](https://sourcegraph.slack.com/archives/CHXHX7XAS/p1614783036122300?thread_ts=1606750767.298900&cid=CHXHX7XAS) this is @sourcegraph/extensibility's area here - is this doable in the short term?

**Comment by mrnugget** [comment]
Because @umpox asked for examples of other dev tools that have a hover tooltip: here's a video of me showing the ~same cursor movements in VS Code vs on Sourcegraph


https://user-images.githubusercontent.com/1185253/109825371-0c39e400-7c3a-11eb-81a9-76bb555d4e30.mp4

You'll see that the delay in VS Code is also short and it's also possible to make the hover disappear, but it's *far* easier to move the cursor to the hover than it is on Sourcegraph

**Comment by Joelkw** [comment]
Noting related to this [issue](https://github.com/sourcegraph/sourcegraph/issues/17065) on hover areas.
