### ISSUE TITLE
Sometimes it takes a while for the tooltip to come up, but there's no feedback showing that it's going to happen

### ISSUE THREAD

**Issue by ijt** [sourcegraph/codeintellify#93]
I saw it today on this pull request: https://github.com/google/go-cloud/pull/1342/files. I hovered the mouse pointer over an identifier I wanted to know more about, but nothing happened. I assumed the Sourcegraph plugin wasn't working at all in this case. I tried a few more times, reloading the page, and eventually it worked. It would be helpful to see some indication that Sourcegraph is processing so it's clear that it isn't just failing.

**Comment by felixfbecker** [comment]
Closing as solved with #251
